# Generated by Django 4.0.3 on 2022-03-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('sex', models.BooleanField()),
                ('sport_on_week', models.SmallIntegerField()),
                ('no_eats_days_per_week', models.SmallIntegerField()),
                ('eats_per_day', models.SmallIntegerField()),
                ('phone_number', models.TextField()),
                ('type_diet', models.TextField()),
            ],
        ),
    ]
