# Generated by Django 4.0.1 on 2022-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.SmallIntegerField()),
                ('proteins', models.SmallIntegerField()),
                ('fats', models.SmallIntegerField()),
                ('carbohydrates', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
