# Generated by Django 4.0.1 on 2022-04-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_product_options_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(),
        ),
    ]
