# Generated by Django 4.0.1 on 2022-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_product_calories_alter_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Шкала измерения',
                'verbose_name_plural': 'Шкалы измерения',
            },
        ),
    ]
