# Generated by Django 4.0.1 on 2022-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_measurescale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureScaleCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_from', models.IntegerField()),
                ('ms_to', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'unique_together': {('ms_from', 'ms_to')},
            },
        ),
    ]
