# Generated by Django 4.0.1 on 2022-04-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_measurescalecourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurescalecourses',
            options={'verbose_name': 'Курс шкал', 'verbose_name_plural': 'Курсы шкал'},
        ),
    ]
