# Generated by Django 4.0.1 on 2022-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True),
        ),
    ]
