# Generated by Django 4.0.1 on 2022-04-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_dish_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
