# Generated by Django 4.0.1 on 2022-04-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_dish_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
        ),
    ]
