# Generated by Django 4.0.1 on 2022-04-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_menu_alter_meal_type_of_meal_template_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.day')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
            options={
                'verbose_name': 'День в меню',
                'verbose_name_plural': 'Дни в меню',
                'unique_together': {('menu', 'day')},
            },
        ),
    ]
